[package]
name = "sudoku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate_type = ["cdylib"]


[dependencies]
wasm-bindgen = "0.2"
rand = { version = "0.6.5", features = ["wasm-bindgen"] }
